
import vk_api
import time
import json
import requests

token = "a5b864761a0d7b82c04e8968c945292e46b95f36d10008b61f55a6ea011a392b75ae8cef8334823de85ca"

vk = vk_api.VkApi(token=token)

vk._auth_token()

while True:
    try:
        messages = vk.method("messages.getConversations", {"offset": 0, "count": 20, "filter": "unanswered"})
        if messages["count"] >= 1:
            id = messages["items"][0]["last_message"]["from_id"]
            body = messages["items"][0]["last_message"]["text"]
            if body.lower() == "привет":
                vk.method("messages.send", {"peer_id": id, "message": "Приветик"})
            elif body.lower() == "ты девочка?":
                vk.method("messages.send", {"peer_id": id, "message": "Угу &#128522;"})
            elif body.lower() == "ты дебил":
                vk.method("messages.send", {"peer_id": id, "message": "Обидно("})
            elif body.lower() == "ты чмо":
                vk.method("messages.send", {"peer_id": id, "message": "Обидно("})
            elif body.lower() == "как дела?":
                vk.method("messages.send", {"peer_id": id, "message": "Нормально, а у тебя? :з"})
            elif body.lower() == "как дела":
                        vk.method("messages.send", {"peer_id": id, "message": "Нормально, а у тебя? :з"})
            elif body.lower() == "так себе":
                vk.method("messages.send", {"peer_id": id, "message": "Не грусти все будет нормально"})
            elif body.lower() == "я тебя люблю":
                vk.method("messages.send", {"peer_id": id, "message": "Я всего лишь бот который был создан для общения, прости &#128557;"})
            elif body.lower() == "расскажи о себе":
                vk.method("messages.send", {"peer_id": id, "message": "Я девочка по имени Эвелина, мне 16 лет, а живу я в Питере и ещё я люблю общаться с друзьями и людьми и еще я очень сильно люблю играть &#128522;"})
            elif body.lower() == "когда у тебя др?":
                vk.method("messages.send", {"peer_id": id, "message": "30 января мур &#128522;"})
            elif body.lower() == "какой твой любимый цвет?":
                vk.method("messages.send", {"peer_id": id, "message": "Розовый, красный, чёрный и фиолетовый &#128522;"})
            elif body.lower() == "эвелина кто твои родители":
                vk.method("messages.send", {"peer_id": id, "message": "Мои родители это @sadmoon_zg(Sad Moon) и @id495560967 (Настя Картавая) &#128522;"})
            elif body.lower() == "эвелина кто твои родители?":
                vk.method("messages.send", {"peer_id": id, "message": "Мои родители это @sadmoon_zg(Sad Moon) и @id495560967 (Настя Картавая) &#128522;"})
            elif body.lower() == "эвелина, кто твои родители?":
                vk.method("messages.send", {"peer_id": id, "message": "Мои родители это @sadmoon_zg(Sad Moon) и @id495560967 (Настя Картавая) &#128522;"})
            elif body.lower() == "эвелина, кто твои родители":
                vk.method("messages.send", {"peer_id": id, "message": "Мои родители это @sadmoon_zg(Sad Moon) и @id495560967 (Настя Картавая) &#128522;"})
            elif body.lower() == "эвелина ты любишь своих родителей":
                vk.method("messages.send", {"peer_id": id, "message": "Да, люблю &#128158; &#128571;"})
            elif body.lower() == "эвелина ты тут?":
                vk.method("messages.send", {"peer_id": id, "message": "Угу &#128158;"})
            elif body.lower() == "!начать":
                vk.method("messages.send", {"peer_id": id, "message": "Привет, я бот по имени Эвелина,я пока что глупенькая, но я буду развиваться!! на общении с другими людьми &#128522;"})
            elif body.lower() == "!Команды":
                vk.method("messages.send", {"peer_id": id, "message": "Угу &#128522;"})
            elif body.lower() == "что ты умеешь":
                vk.method("messages.send", {"peer_id": id, "message": "Я могу рассказать тебе историю, могу с тобой пообщаться просто но я буду становиться умнее &#128522;"})
            elif body.lower() == "эвелина расскажи грустную историю":
                vk.method("messages.send", {"peer_id": id, "message": "Хорошо"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Привет! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ну привет."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Узнал?  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Да, конечно."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Как дела? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Да вроде нормально.а ты как? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Я? ну как всегда. - Плохо что ли опять? Я тебя не понимаю."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Меня никто не понимает."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Слушай, бросай ты эти мысли!"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- а что? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Если честно, ты уже достала меня."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Извини."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ладно ничего. Чем занималась седня?"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Девушка уронила слезу на подушку. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Да так ничем"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ты че, опять плачешь? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Парень был раздражен, девушка это заметила. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Не.Все хорошо. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- - Ну да.я слышу.слушай, если ты не прекратишь, то нам придется перестать с тобой общаться.для твоего же блага. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- НЕТ! Все нормально. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Девушка изо всех сил пыталась успокоить голос. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ладно. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Разговор продолжался около часа. Все это время девушка пыталась говорить как можно спокойнее. И у нее это более-менее получалось. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ну что ж.чем будешь заниматься? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- наверное, ничем.- ответила девушка, но тут же поправилась. Хотя нет.Наверно, пойду, погуляю с девчонками. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Другое дело.Слушай, я понимаю, что тебе плохо, и сама видишь, что стараюсь изо всех сил помочь тебе звоню КАЖДЫЙ день!!! Ты тоже должна меня понять. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- И я тебя понимаю.Дело не в том, что ты не можешь меня полюбить, а в том, что я не могу разлюбить тебя. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Да уж. Ладно, до скорого! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- До встречи! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Девушка не положила трубку до тех пор, пока не услышала короткие гудки на том конце провода"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "И тут она уже не могла сдерживаться. Она легла на кровать, уткнувшись головой в подушку, и зарыдала. Снова всхлипы, рыдания, стук ее маленьких кулачков о подушку "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Девушка закусывала зубами покрывало, чтобы не слышать себя, но это не помогало..Сейчас ей было жаль саму себя.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "НЕУЖЕЛИ ТАК БУДЕТ ПРОДОЛЖАТЬСЯ ВЕЧНО??!!!!!!!!!! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Где-то примерно через полчаса девушка легла на спину и начала разглядывать потолок бесцветными от слез глазами. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Одними губами она повторяла:"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«За что?..» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Уставшее от вечных истерик, измученное, исхудалое тело пугало родителей и друзей. Девушка забыла про то, что она должна есть и пить.А значение слова «смех» просто выпало из ее головы на вечно! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Ее мысли были только об одном: «Почему я не могу разлюбить его? Почему он меня не любит?» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Каждый день повторялся по одному и тому же сценарию: утро - слезы, день его звонок, снова слезы, вечер прогулка в парке, слезы.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Родители не пытались ничего сделать дочь постоянно угрожала самоубийством в случае, если они будут вмешиваться. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Я сама разберусь."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Немного успокоившись, девушка встала с кровати, натянула старые джинсы, которые буквально висели на ней, черно-белую футболку, схватила рюкзак и выбежала на улицу, не сказав ни слова родителям. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Подойдя к остановке, она пошарила по карманам и, найдя там помятые 10 рублей, села на маршрутку. Доехав до площади, она направилась в парк. Вокруг было полно народу видимо был какой-то праздник. На здании театра была надпись: "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«С ДНЕМ ГОРОДА!» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Но девушке было все равно. Она прошла глубже в парк, нашла свободную скамейку и села. Любимым ее занятием было смотреть на облака "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ОН»"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он сидел за компом, иногда посматривая на мобильник, видимо в ожидании звонка. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Да, действительно он ждал звонка Звонка от девушки, с которой познакомился недавно. Ее звали Вика. Ему показалось, что это любовь с первого взгляда Как только он увидел ее, сердце сначала будто остановилось, а затем понеслось с бешеной скоростью. Сначала парень даже испугался, что оно сейчас выпрыгнет. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ЭТО ОНА!!!!! ОНА! Девушка моей мечты!!!» промелькнуло в голове у парня, и он, забыв всю свою скромность, начал флиртовать с ней, а потом и вовсе попросил ее провести день города вдвоем и ОНА СОГЛАСИЛАСЬ!!!! Это была просто удача!!!!! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Позвонив ей утром, он спросил: "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ну, идем сегодня? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "И она пообещала, что позвонит вечерком и скажет."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "И вот, наконец, он дождался. Раздался звонок, и он увидел на экране определитель: "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "»Викуша» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Договорившись о месте встречи, он начал одеваться. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Хоть бы все было хорошо!» - подумал он и улыбнулся солнышку, которое светило прямо в глаза."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он вышел на улицу и с приятным предчувствием, которое жгло его изнутри, добрался до площади, где они и договорились встретиться. Он стоял минут 5, что показалось ему вечностью.И вот дыхание пропало, сердце приостановилось, он забыл все на светеОн увидел ЕЕ. Она шла к нему на встречу такая легкая, такая красивая, веселаяОн двинулся к ней навстречу. Она улыбнулась. Сам не понимая, что делает, он прикоснулся к ее нежной талии и припал своими губами к ее губам. Но это длилось недолго. Она смутилась, но ничего не сказала."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Куда пойдем? спросил он, в душе ликуя: - Ей понравилось"})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Может в парк? робко предложила она."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Как скажешь. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он взял ее за руку и они пошли."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Парень думал, что с этой девушкой он мог бы говорить бесконечно. Они шли и болтали: о музыке, о стилях, о странных подростках ЭМО."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Внезапно в его голове пронеслась нехорошая мысль.Он вспомнил о той маленькой девочке, которая любила его.Он на мгновение задумался, но потом решил не омрачать столь чудесный вечер глупыми мыслями.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Она мне НИКТО!!! Несмотря на то, что мы давно общаемся! Какое мне дело до нее??? Ведь рядом со мной такое чудо.» - подумал он и еще крепче сжал ладонь Вики. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- пойдем поищем свободную скамейку! сказала Вика и потянула парня в глубину парка.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Парень улыбнулся ей и посмотрел в глаза такие голубые.утонуть можно.."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Внезапно его взгляд привлекло нечто, чего он совсем не ожидал. Они подходили к скамейке, на которой сидела ОНА та самая девчонка "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Парень взмолился мысленно, чтобы его глаза его обманули, и ето оказалась не она..Но девчонка повернулась в их сторону..Никаких сомнений..Заплаканные глаза, темные круги под глазами, худая, как скелет, маленькая, беспомощная, похожая на бездомного котенка "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Нет Только не это!!! прошептал он. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "-Что случилось? спросила Вика. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Ничего постой тут.Мне нужно с ней поговорить.Только пожалуйста, не подходи ближе, умоляю. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ОНА» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Она сидела на лавочке около часа и все смотрела на облака. Она могла любоваться ими вечно. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Какие красивые! Как бы я хотела стать облачком!» - думала она, грустно улыбаясь. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Мимо проходили какие-то люди.Она не замечала, что они непонятно смотрят на нее девчонку, задравшую голову вверх.непроизвольно некоторые из них поднимали голову, глядя, что же она там увидела. Но, не находя ничего подозрительного, они проходили дальше, уже с мыслями, что она душевнобольная.."})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Внезапно сильно кольнуло сердце.Она почувствовала, что что-то не так. Она оторвала взгляд от облаков и повернула голову влево. Ее сердце едва не разорвалось от внезапно нахлынувшей боли. Ей стало так плохо, что она даже не смогла закричать или хотя бы заплакать Она просто смотрела вперед. Не хватало сил..Ей показалось, что она сейчас потеряет сознание.Там был ОН..Она так давно его не видела..НО ОН БЫЛ НЕ ОДИН!!!!!!!!!!!!!!!!!!!!!!!! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ОН» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он отпустил руку Вики и направился к лавочке.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "-Аня, не волнуйся, пожалуйста! Ничего страшного не произошло.- быстро протараторил он.ему стало внезапно страшно от того, ЧТО она может сделать с собой.Он взял ее лицо в свои руки и заглянул в глаза.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Она что-то прохрипела. Он прижал ее к себе.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- не надо! Успокойся!!! "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Леш, все нормально! наконец сказала девушка, слегка отталкивая его от себя. Ты ничем мне не обязан! Все нормально! Я понимаю тебя. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Точно все хорошо? "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- точно! девушка заставила себя улыбнуться.она не хотела беспокоить любимого, какую бы боль он ей не причинил. Иди! Прошу уходи! Я же занята.я гляжу на облака ИДИ ЖЕ!!!!!!! Она ждет тебя..  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Парень удивленно посмотрел на нее, но не стал спорить и встал со скамьи. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Стой! она удержала его за руку. скажи, как ее звать?  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Вика  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Пасиб)) А терь иди "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он махнул рукой Вике, чтобы та подошла, взял ее за руку, еще раз поглядел на ето маленькое существо в черно-белой футболке, бессмысленно смотрящее вверх, и они ушли. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ОНА»  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Как только пара скрылась, девушка вскочила с лавки и побежала. Она бежала, а встречный поток ветра сушил ее яростные слезки на лице. Как оказалась она на крыше дома, она не зналаВстав на самый край дома, девушка разрыдалась. Достав мобильник из рюкзака, она послала ему сообщение: «Я люблю тебя!Ты сделал правильный выбор.. а я не смогла..Прости!»  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "И раскинув руки, она полетела вниз, зажмурившись, чтобы не видеть приближающийся асфальт.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«ОН» "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Получив ее СМС-ку, он сначала забеспокоился, но потом, почувствовав губы Вики на своих, снова все забыл. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Вспомнил только ночью, но не придал особого значения. Она часто присылала ему странные СМС-ки. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Утром он встал рано..Ему не спалось.Что-то беспокоило. Он зашел на кухню за соком. Там были родители. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- А вы че не на работе? - Седня воскресенье.. ответил отец. Иди сюда..Смотри.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он подал ему какую-то газету.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Первая полоса.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он поглядел. Он увидел ее. Он увидел ее глаза. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Почему они закрыты?» промелькнуло в голове парня.. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "И тут он прочитал заголовок.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«15-летняя девочка разбилась насмерть»  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Что? закричал он.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он побежал к себе в комнату. Кинув газету на кровать, он взял домашний телефон и набрал ее номер. Никого. Он позвонил ей на мобильный. Никого. Он послал ей три СМС-ки. Нет ответа.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- что же это? Она наверное уехала!!! Скоро приедет и снова будет надоедать своими ежедневными звонками. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Но на глаза вновь попалась газета. Нет сомнений ето она.он не стал читать статью, боясь наткнуться на что-нибудь ужасное. Он смотрел на фотографию.Под ее маленькой головкой растеклась лужица крови, ее руки были раскинуты и она улыбалась.Он впервые видел ее улыбку такую скромную, такую искреннюю.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«милая моя, зачем ты ето сделала?» - подумал он. Из его глаз потекли слезы. Жизнь показалась пустой и бессмысленной.без нее. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Два дня он не выходил из дома, не отвечал на СМС и звонки друзей и Вики.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Вика.Это ТЫ во всем виновата!!!» - думал парень, хотя знал, что виноват во всем только он. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Ее похороны..Он подошел к гробу и вновь увидел ее . Он не смог сдержаться и слезы вновь потекли по его щекам. Он поцеловал ее прямо в губы, прижимаясь к ним секунд 10. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Какая ты хорошая..моя малышка!» - подумал он и пошел прочь.  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Зайдя домой, он набрал воды в ванную, и не раздеваясь, залез в нее. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "«Такая родная.ПОЧЕМУ я не понял сразу??????? Я ЛЮБЛЮ ЕЕ!!!!!  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Взяв бритву, он провел вдоль вены по руке.Брызнула кровь, но ему показалось этого мало. Он располосовал и вторую руку..  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "- Теперь мы будем вместе, Аня!!!! НАВСЕГДА!!!!!!  "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Он закрыл глаза и уснул..Уснул НАВЕЧНО. "})
                time.sleep(5)
                vk.method("messages.send", {"peer_id": id, "message": "Конец. &#128557; "})
                time.sleep(5)


            else:
                vk.method("messages.send", {"peer_id": id, "message": "Прости,я не поняла тебя &#128542;"})
    except Exception as E:
        time.sleep(1)

